if: tag IS present
language: cpp
os: linux
dist: xenial
compiler: clang
script:
- svn -q co https://svn.code.sf.net/p/sbml/code/branches/libsbml-experimental@26045
- cd libsbml-experimental
- svn log -l 1
- mkdir build
- cd build
- whereis libxml2.a
- cmake -LA ..
- cmake -DENABLE_SPATIAL=ON -DCMAKE_INSTALL_PREFIX=install -DWITH_CPP_NAMESPACE=ON -DLIBSBML_SKIP_SHARED_LIBRARY=ON -DWITH_BZIP2=OFF -DWITH_ZLIB=OFF -DLIBXML_LIBRARY=/usr/lib/x86_64-linux-gnu/libxml2.a ..
- make -j2 install
- ls
- cd install
- ls
before_deploy:
  tar -zcvf libsbml-static-linux.tgz include/* lib/libsbml-static.a
deploy:
  provider: releases
  api_key:
    secure: BFtmptZuPhWFbnBC1Xvkn2hsKlzbHDGqfggTGnjnT+CEZ68xoPntvaVyetAtCB4oZAenj+dB4/Ut1HaoLnFu2k+E6/ytMBsXOyvke9GFz+7dxzgO8wgnVglVj2QRQ2LzQ5BszKE9UN4ZLSaHi1UmLuENiatBdOKE/SAhkTQKnJ618AqxE0MTGtHDuEMcMRPMGgePd16g+W0wXBFXfIVWgTPAa5E+r8QqBEfQeIBYwbLG01W/X4uPYAc4ZQKdDB9duTTrc2BA0quRRZmCpn5mLM+uVEHiU4j+0QKjXOdZqc79PuiYvxbi5VCFTZzGKWyXi/bZS9SPDyYU/7eeGqH7scb9IIcSia8pfbrg15QAEqRGkL7Xu8BtFEe2hiHeK29OpPTsbk9rCGucWwBNjkXtul684aOrpQ5Sp/G6RsMgHdMNsnoacbMHMF89FtH3EDcId9QklJzrh+2yIbKJaWZydeuHOnMa3agS7DlMtp3QI+WjiAufZock5hjJWrwTonD80jOKlPrXHqxC0edhXnpvk9DojmWvCg5/Yj46UwIfskfUtzy/J+6y2npHxyhlgXDS02yRB4KSqdZQrpLwzLFIV3+zPdpiqzlaQCOC+inpd1ll+Do4NddYrzRFZDLy+x2QguYDLwhnJDg8PaM+EH9JAwmtOkapfPyZvDWkDLK4cwk=
  file:
    - "libsbml-static-linux.tgz"
  skip_cleanup: true
  on:
    repo: lkeegan/libsbml-static-linux
    tag: true
    all_branches: true
notifications:
  email: false
