# windows release build: mingw64 g++ from MSYS2 (currently 8.2.0) on Windows Server 2012 R2
image:
  - Visual Studio 2015
install:
  - set PATH=C:\msys64\usr\bin;%PATH%

build_script:
  - cp build.sh C:\msys64\home\appveyor\.
  - bash -l build.sh

after_build:
  - cd "C:\tarball"
  - 7z a %APPVEYOR_BUILD_FOLDER%\libsbml-static-win32.zip *

artifacts:
  - path: libsbml-static-win32.zip
    name: libsbml-static-win

deploy:
  description: 'windows release'
  provider: GitHub
  artifact: libsbml-static-win
  auth_token:
    secure: AzIgTar/Vk7S6hA8HAZAImacEIrbwmfrR6PJ+qHuAQHuLyPSAAcpI5rl/w6BumKp
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
