# windows release build: mingw64 g++ from MSYS2 (currently 9.1.0) on Windows Server 2012 R2
image:
  - Visual Studio 2015
install:
  - set PATH=C:\msys64\usr\bin;%PATH%

build_script:

  # download LLVM static libraries
  - appveyor DownloadFile "https://github.com/lkeegan/llvm-static/releases/latest/download/llvm-static-windows.zip"
  - 7z x llvm-static-windows.zip
  - dir
  - mkdir C:\libs
  - mv include C:\libs\.
  - mv lib C:\libs\.
  - mv bin C:\libs\.
  - dir "C:\libs"

  - cp build.sh C:\msys64\home\appveyor\.
  - bash -l build.sh

after_build:
  - cd "C:\libs"
  - 7z a %APPVEYOR_BUILD_FOLDER%\libsbml-static-windows.zip *

artifacts:
  - path: libsbml-static-windows.zip
    name: libsbml-static-windows

deploy:
  description: ''
  provider: GitHub
  artifact: libsbml-static-windows
  auth_token:
    secure: AzIgTar/Vk7S6hA8HAZAImacEIrbwmfrR6PJ+qHuAQHuLyPSAAcpI5rl/w6BumKp
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
